# Generated by Django 5.2.13 on 2026-05-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0067_slackwritemessageworkflowaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('builder', 'path')},
        ),
    ]
