# Generated by Django 5.2.12 on 2026-03-24 07:45

import baserow.contrib.builder.elements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0068_alter_page_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuelement",
            name="variant",
            field=models.JSONField(
                blank=True,
                db_default={
                    "desktop": "expanded",
                    "smartphone": "compact",
                    "tablet": "compact",
                },
                default=baserow.contrib.builder.elements.models.get_default_variant,
                help_text=(
                    "The menu variant (expanded or compact) for each device type"
                ),
            ),
        ),
    ]
