# Generated by Django 5.2.13 on 2026-05-07 07:08

import django.db.models.deletion
from django.db import migrations, models


def backfill_original_workflow(apps, schema_editor):
    AutomationWorkflowHistory = apps.get_model(
        "automation", "AutomationWorkflowHistory"
    )
    AutomationWorkflowHistory.objects.filter(original_workflow__isnull=True).update(
        original_workflow_id=models.F("workflow_id")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0028_automationworkflowhistory_original_workflow_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_original_workflow,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='automationworkflowhistory',
            name='original_workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_histories', to='automation.automationworkflow'),
        ),        
    ]
