# Generated by Django 5.2.13 on 2026-04-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0209_optimize_pending_search_value_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimportjob',
            name='importer_type',
            field=models.TextField(blank=True, help_text='The frontend importer identifier used to parse the file.', null=True),
        ),
        migrations.AddField(
            model_name='fileimportjob',
            name='original_file_name',
            field=models.TextField(blank=True, help_text='The original name of the uploaded file.', null=True),
        ),
    ]
